# Generated by Django 3.2.16 on 2024-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_user_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
    ]
